version: "3"
services:

  kong:
    build:
      context: .
      dockerfile: ./debug/Dockerfile
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_STATUS_LISTEN=0.0.0.0:8006
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PLUGINS=bundled,api-catalog-harvester
      - KONG_PLUGINSERVER_API_CATALOG_HARVESTER_START_CMD=/entrypoint.sh
      - KONG_PLUGINSERVER_API_CATALOG_HARVESTER_QUERY_CMD=/usr/local/bin/api-catalog-harvester -dump
      - KONG_PLUGINSERVER_NAMES=api-catalog-harvester
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8006:8006"
      - "40000:40000"
    volumes:
      - ${PWD}/kong.yml:/etc/kong/kong.yml
      - ${PWD}/logs:/logs
      - ${PWD}/repository:/repository
      - ${PWD}/snapshots:/snapshots
